Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.has_ssh = true
  end
  config.ssh.port = 22
  config.ssh.username = "docker3"
  config.vm.network :forwarded_port, guest: 22, host: 1234
end
